### PR TITLE
Fix crate name inconsistencies

### PR DESCRIPTION
**Pull request by barskern**
If a crate as a different name from its library (see example below) the
docs are generated into a folder with the name of the target. Hence
instead of using the package name, we should use the target name.

```toml
[package]
name = "my-cratename"

[lib]
name = "my-actual-cratename"
```

Currently it selects the first target, which means that it might select
a binary as the target. Normally on only generates docs for a library,
so instead of choosing the first target we could change it to choose the
first library target and then fallback to a binary target if there are
no library targets.

Related to #4

### CODE REVIEW

**Comment by qmx** [comment]
I think you're on to something - do you have any ideas on how can we add some automated tests to make sure we don't end up breaking the other cases?

**Comment by barskern** [comment]
We could use the `Cargo.toml` of some popular crates and run `cargo doc --no-deps`. Then we could check the name of the folder which was generated in the `target/doc` folder.

**Comment by qmx** [comment]
cool, I was looking at the other part of the equation, how to drive cargo from a test - still haven't figured a good way of doing this

also, TIL about `doc --no-deps` :)

**Comment by barskern** [comment]
> cool, I was looking at the other part of the equation, how to drive cargo from a test - still haven't figured a good way of doing this

Hmm yeah that's a good point.. I guess the "cleanest" way is to depend on `cargo` as a dev dependency and use that to run commands (e.g [`cargo doc`](https://docs.rs/cargo/0.39.0/cargo/ops/fn.doc.html).

**Comment by barskern** [comment]
@qmx I got it working now for testing here. Now we just need to add some more potential crates in assets (**only** their `Cargo.toml` and a `src/lib.rs`).

**Comment by qmx** [comment]
@barskern hey, sorry for taking so long to come back to this! (life has been pretty crazy)

This looks great! I tested locally and it looks fine!

I'm going to merge this and we can add more test cases on follow-up PRs.

Thanks for your patience!

**Comment by barskern** [comment]
No worries! It's important to put life first 😊

**Pull request merged**
