### PR TITLE
Use lazy_static to only parse crate info once

### PR DESCRIPTION
**Pull request by barskern**

### CODE REVIEW

**Comment by qmx** [comment]
Hey @barskern, thanks for the PR! The problem I see here is that we actually have no guarantees that the `Cargo.toml` file will stay the same between invocations. To be able to do what you're suggesting we would probably need to add a `Mutex` to that `lazy_static` ref.

Do you have a specific need that drove this refactoring or was it just "low-hanging fruit"?

**Comment by barskern** [comment]
@qmx I did not think about that. That is a fair point, but I would also say it's reasonable to restart the server if one changes the `Cargo.toml`. I think there are very few cases where it would change.

The main reason I sent the PR is because I have had some issues with it being slow, and hence I figured this was a perhaps small way to improve that. But I doubt it would make a big difference, so I see the benefit of parsing it on every invocation.

**Comment by qmx** [comment]
@barskern shall we just close this one?

**Comment by barskern** [comment]
Yeah let's just close it.

**Pull request closed without merging**
